input.onButtonPressed(Button.A, function () {
	music.setTempo(25)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.setTempo(14)
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.setTempo(14)
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.setTempo(50)
    for (let index = 0; index < 3; index++) {
        music.playTone(294, music.beat(BeatFraction.Quarter))
        music.playTone(294, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Eighth))
    }
    music.setTempo(40)
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.setTempo(50)
    for (let index = 0; index < 2; index++) {
        music.playTone(294, music.beat(BeatFraction.Quarter))
        music.playTone(294, music.beat(BeatFraction.Quarter))
        music.playTone(262, music.beat(BeatFraction.Eighth))
    }
    music.setTempo(47)
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 1; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(392, music.beat(BeatFraction.Eighth))
            music.playTone(440, music.beat(BeatFraction.Eighth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(349, music.beat(BeatFraction.Eighth))
        music.playTone(330, music.beat(BeatFraction.Sixteenth))
        music.playTone(349, music.beat(BeatFraction.Sixteenth))
        music.playTone(330, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(392, music.beat(BeatFraction.Eighth))
            music.playTone(440, music.beat(BeatFraction.Eighth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(392, music.beat(BeatFraction.Eighth))
        music.playTone(440, music.beat(BeatFraction.Eighth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
        music.playTone(440, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 3; index++) {
            music.playTone(392, music.beat(BeatFraction.Eighth))
            music.playTone(440, music.beat(BeatFraction.Eighth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
            music.playTone(262, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(349, music.beat(BeatFraction.Eighth))
        music.playTone(330, music.beat(BeatFraction.Sixteenth))
        music.playTone(349, music.beat(BeatFraction.Sixteenth))
        music.playTone(330, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.playTone(294, music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
        music.playTone(349, music.beat(BeatFraction.Eighth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
        music.playTone(349, music.beat(BeatFraction.Sixteenth))
        music.playTone(392, music.beat(BeatFraction.Eighth))
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
        music.playTone(440, music.beat(BeatFraction.Sixteenth))
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(440, music.beat(BeatFraction.Sixteenth))
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
    }
    for (let index = 0; index < 1; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(784, music.beat(BeatFraction.Eighth))
            music.playTone(880, music.beat(BeatFraction.Eighth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(784, music.beat(BeatFraction.Eighth))
            music.playTone(880, music.beat(BeatFraction.Eighth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.playTone(1318, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 3; index++) {
            music.playTone(784, music.beat(BeatFraction.Eighth))
            music.playTone(880, music.beat(BeatFraction.Eighth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
            music.playTone(523, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(523, music.beat(BeatFraction.Eighth))
    }
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.setTempo(47)
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.rest(music.beat(BeatFraction.Eighth))
    }
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.setTempo(47)
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(587, music.beat(BeatFraction.Eighth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(349, music.beat(BeatFraction.Eighth))
    }
    music.playTone(392, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(330, music.beat(BeatFraction.Eighth))
    }
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(440, music.beat(BeatFraction.Eighth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(440, music.beat(BeatFraction.Eighth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(440, music.beat(BeatFraction.Eighth))
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.setTempo(47)
    music.playTone(466, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(349, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(262, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Eighth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Eighth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(932, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Eighth))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(932, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 6; index++) {
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 6; index++) {
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 6; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.setTempo(62)
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(831, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 2; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(622, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(622, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.setTempo(65)
    for (let index = 0; index < 2; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(622, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 1; index++) {
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(622, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(622, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(1865, music.beat(BeatFraction.Sixteenth))
    music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.setTempo(130)
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(165, music.beat(BeatFraction.Eighth))
    music.playTone(175, music.beat(BeatFraction.Sixteenth))
    music.playTone(196, music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.setTempo(46)
    music.playTone(175, music.beat(BeatFraction.Sixteenth))
    music.playTone(233, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(415, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(698, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(466, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(523, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.setTempo(40)
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(2093, music.beat(BeatFraction.Sixteenth))
    music.playTone(2349, music.beat(BeatFraction.Sixteenth))
    music.playTone(2637, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.rest(music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(1661, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(1568, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(1661, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(1397, music.beat(BeatFraction.Eighth))
    music.setTempo(78)
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.setTempo(45)
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.setTempo(78)
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.setTempo(44)
    for (let index = 0; index < 1; index++) {
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(523, music.beat(BeatFraction.Quarter))
    }
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 1; index++) {
        music.playTone(698, music.beat(BeatFraction.Quarter))
        music.playTone(659, music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        music.playTone(523, music.beat(BeatFraction.Quarter))
    }
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(349, music.beat(BeatFraction.Eighth))
    }
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(330, music.beat(BeatFraction.Whole))
    music.setTempo(44)
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Whole))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.setTempo(50)
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(1046, music.beat(BeatFraction.Quarter))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.setTempo(64)
    for (let index = 0; index < 1; index++) {
        music.playTone(587, music.beat(BeatFraction.Half))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(698, music.beat(BeatFraction.Half))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(784, music.beat(BeatFraction.Half))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(784, music.beat(BeatFraction.Half))
    }
    music.playTone(880, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 1; index++) {
        music.playTone(880, music.beat(BeatFraction.Half))
    }
    music.setTempo(31)
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(932, music.beat(BeatFraction.Half))
    music.setTempo(31)
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.setTempo(45)
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1568, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.setTempo(38)
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.setTempo(40)
    for (let index = 0; index < 2; index++) {
        music.playTone(784, music.beat(BeatFraction.Quarter))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(880, music.beat(BeatFraction.Quarter))
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.setTempo(45)
    music.playTone(932, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.setTempo(70)
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Sixteenth))
    music.playTone(196, music.beat(BeatFraction.Sixteenth))
    music.playTone(175, music.beat(BeatFraction.Sixteenth))
    music.playTone(165, music.beat(BeatFraction.Sixteenth))
    music.playTone(147, music.beat(BeatFraction.Sixteenth))
    music.playTone(131, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Whole))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(784, music.beat(BeatFraction.Whole))
    music.setTempo(47)
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(988, music.beat(BeatFraction.Eighth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.setTempo(47)
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(988, music.beat(BeatFraction.Eighth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(988, music.beat(BeatFraction.Eighth))
    }
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(1046, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.setTempo(130)
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1046, music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(523, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.setTempo(52)
    for (let index = 0; index < 1; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(440, music.beat(BeatFraction.Eighth))
            music.playTone(494, music.beat(BeatFraction.Eighth))
            for (let index = 0; index < 2; index++) {
                music.playTone(330, music.beat(BeatFraction.Sixteenth))
                music.playTone(294, music.beat(BeatFraction.Sixteenth))
            }
        }
        music.playTone(392, music.beat(BeatFraction.Eighth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(330, music.beat(BeatFraction.Eighth))
        music.playTone(294, music.beat(BeatFraction.Eighth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(440, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(330, music.beat(BeatFraction.Sixteenth))
            music.playTone(294, music.beat(BeatFraction.Sixteenth))
        }
    }
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(440, music.beat(BeatFraction.Eighth))
            music.playTone(494, music.beat(BeatFraction.Eighth))
            for (let index = 0; index < 2; index++) {
                music.playTone(330, music.beat(BeatFraction.Sixteenth))
                music.playTone(294, music.beat(BeatFraction.Sixteenth))
            }
        }
        music.playTone(392, music.beat(BeatFraction.Eighth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(330, music.beat(BeatFraction.Eighth))
        music.playTone(294, music.beat(BeatFraction.Eighth))
    }
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        for (let index = 0; index < 3; index++) {
            music.playTone(880, music.beat(BeatFraction.Eighth))
            music.playTone(988, music.beat(BeatFraction.Eighth))
            for (let index = 0; index < 2; index++) {
                music.playTone(659, music.beat(BeatFraction.Sixteenth))
                music.playTone(587, music.beat(BeatFraction.Sixteenth))
            }
        }
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Sixteenth))
        music.playTone(740, music.beat(BeatFraction.Sixteenth))
        music.playTone(659, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.playTone(988, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(659, music.beat(BeatFraction.Sixteenth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
        }
    }
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1568, music.beat(BeatFraction.Eighth))
    music.playTone(1480, music.beat(BeatFraction.Sixteenth))
    music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.playTone(988, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(659, music.beat(BeatFraction.Sixteenth))
            music.playTone(587, music.beat(BeatFraction.Sixteenth))
        }
    }
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
})
