input.onButtonPressed(Button.A, function () {
	music.setTempo(51)
    for (let index = 0; index < 1; index++) {
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(2093, music.beat(BeatFraction.Half))
        music.playTone(1568, music.beat(BeatFraction.Half))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(784, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(2093, music.beat(BeatFraction.Half))
        music.playTone(1568, music.beat(BeatFraction.Half))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1397, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(784, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(2093, music.beat(BeatFraction.Half))
        music.playTone(1568, music.beat(BeatFraction.Half))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1245, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(784, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(2093, music.beat(BeatFraction.Half))
        music.playTone(1568, music.beat(BeatFraction.Half))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1397, music.beat(BeatFraction.Quarter))
        music.playTone(1568, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1397, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(932, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Whole))
        music.rest(music.beat(BeatFraction.Sixteenth))
        for (let index = 0; index < 1; index++) {
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(208, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Quarter))
            music.playTone(294, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(196, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(208, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Quarter))
            music.playTone(349, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Half))
        }
        for (let index = 0; index < 3; index++) {
            music.playTone(1661, music.beat(BeatFraction.Eighth))
        }
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Quarter))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Half))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 3; index++) {
            music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        }
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Quarter))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 1; index++) {
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(208, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Quarter))
            music.playTone(294, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(196, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(175, music.beat(BeatFraction.Quarter))
            music.playTone(208, music.beat(BeatFraction.Quarter))
            music.playTone(262, music.beat(BeatFraction.Quarter))
            music.playTone(311, music.beat(BeatFraction.Quarter))
            music.playTone(349, music.beat(BeatFraction.Quarter))
            music.playTone(392, music.beat(BeatFraction.Half))
        }
        for (let index = 0; index < 3; index++) {
            music.playTone(1661, music.beat(BeatFraction.Eighth))
        }
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1661, music.beat(BeatFraction.Eighth))
        music.playTone(1865, music.beat(BeatFraction.Eighth))
        music.playTone(2093, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Half))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(587, music.beat(BeatFraction.Quarter))
        for (let index = 0; index < 1; index++) {
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1568, music.beat(BeatFraction.Eighth))
            music.playTone(1568, music.beat(BeatFraction.Sixteenth))
            music.playTone(1568, music.beat(BeatFraction.Sixteenth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1174, music.beat(BeatFraction.Sixteenth))
            music.playTone(1174, music.beat(BeatFraction.Sixteenth))
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1174, music.beat(BeatFraction.Quarter))
            music.rest(music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1174, music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Eighth))
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1046, music.beat(BeatFraction.Eighth))
            music.playTone(932, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Eighth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(1174, music.beat(BeatFraction.Quarter))
            music.rest(music.beat(BeatFraction.Eighth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Sixteenth))
            music.playTone(831, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(831, music.beat(BeatFraction.Sixteenth))
            music.playTone(831, music.beat(BeatFraction.Sixteenth))
            music.playTone(831, music.beat(BeatFraction.Eighth))
            music.playTone(932, music.beat(BeatFraction.Eighth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.playTone(1046, music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Eighth))
            music.playTone(831, music.beat(BeatFraction.Eighth))
            music.playTone(784, music.beat(BeatFraction.Eighth))
            music.playTone(784, music.beat(BeatFraction.Sixteenth))
            music.playTone(932, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1245, music.beat(BeatFraction.Quarter))
            music.playTone(932, music.beat(BeatFraction.Quarter))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.rest(music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Sixteenth))
            music.playTone(1245, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1480, music.beat(BeatFraction.Eighth))
            music.playTone(1480, music.beat(BeatFraction.Sixteenth))
            music.playTone(1480, music.beat(BeatFraction.Sixteenth))
            music.playTone(1661, music.beat(BeatFraction.Eighth))
            music.playTone(1480, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Sixteenth))
            music.playTone(1397, music.beat(BeatFraction.Sixteenth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1480, music.beat(BeatFraction.Eighth))
            for (let index = 0; index < 3; index++) {
                music.playTone(1397, music.beat(BeatFraction.Eighth))
            }
            music.playTone(1568, music.beat(BeatFraction.Sixteenth))
            music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        }
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.playTone(932, music.beat(BeatFraction.Sixteenth))
        music.playTone(831, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(831, music.beat(BeatFraction.Sixteenth))
        music.playTone(831, music.beat(BeatFraction.Sixteenth))
        music.playTone(831, music.beat(BeatFraction.Eighth))
        music.playTone(932, music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.rest(music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.playTone(1046, music.beat(BeatFraction.Sixteenth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1865, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1245, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 2; index++) {
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1568, music.beat(BeatFraction.Eighth))
        }
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 1; index++) {
            music.playTone(1174, music.beat(BeatFraction.Eighth))
            music.playTone(1397, music.beat(BeatFraction.Eighth))
            music.playTone(1568, music.beat(BeatFraction.Eighth))
        }
        music.playTone(2093, music.beat(BeatFraction.Eighth))
        music.playTone(1976, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(392, music.beat(BeatFraction.Quarter))
    }
})