input.onButtonPressed(Button.A, function () {
	music.setTempo(45)
    for (let index = 0; index < 1; index++) {
        music.playTone(1976, music.beat(BeatFraction.Eighth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.playTone(1976, music.beat(BeatFraction.Eighth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
    }
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Half))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Quarter))
    }
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Quarter))
    }
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(1108, music.beat(BeatFraction.Quarter))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.playTone(1318, music.beat(BeatFraction.Quarter))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Quarter))
    }
    music.playTone(659, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(1046, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(880, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(831, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 3; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(2637, music.beat(BeatFraction.Half))
    music.playTone(330, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(330, music.beat(BeatFraction.Quarter))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(415, music.beat(BeatFraction.Half))
    music.playTone(440, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Half))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Half))
    music.playTone(523, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Whole))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(1046, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Half))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Quarter))
    music.playTone(2217, music.beat(BeatFraction.Eighth))
    music.playTone(2349, music.beat(BeatFraction.Eighth))
    music.playTone(2637, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(2637, music.beat(BeatFraction.Eighth))
    music.playTone(2349, music.beat(BeatFraction.Eighth))
    music.playTone(2217, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))


    music.setTempo(45)
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1480, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1480, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Half))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1976, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1318, music.beat(BeatFraction.Eighth))
    music.playTone(1108, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(1976, music.beat(BeatFraction.Eighth))
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 2; index++) {
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.playTone(1976, music.beat(BeatFraction.Eighth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
    }
    music.playTone(1760, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
})