input.onButtonPressed(Button.A, function () {
	for (let index = 0; index < 2; index++) {
        music.setTempo(60)
        for (let index = 0; index < 1; index++) {
            music.playTone(262, music.beat(BeatFraction.Eighth))
            music.rest(music.beat(BeatFraction.Eighth))
            music.playTone(262, music.beat(BeatFraction.Eighth))
            music.rest(music.beat(BeatFraction.Eighth))
            music.playTone(659, music.beat(BeatFraction.Eighth))
            music.rest(music.beat(BeatFraction.Eighth))
            music.playTone(392, music.beat(BeatFraction.Eighth))
            music.rest(music.beat(BeatFraction.Eighth))
        }
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(440, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(262, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(440, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Sixteenth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(880, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(988, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Sixteenth))
        music.playTone(1568, music.beat(BeatFraction.Sixteenth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1976, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(2093, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 5; index++) {
            music.rest(music.beat(BeatFraction.Eighth))
        }
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1760, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 3; index++) {
            music.playTone(1046, music.beat(BeatFraction.Quarter))
            music.rest(music.beat(BeatFraction.Quarter))
        }
        music.playTone(1046, music.beat(BeatFraction.Quarter))
        music.rest(music.beat(BeatFraction.Quarter))
        music.setTempo(60)
        music.playTone(1568, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 4; index++) {
            music.playTone(1046, music.beat(BeatFraction.Quarter))
            music.rest(music.beat(BeatFraction.Quarter))
        }
        music.playTone(784, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.rest(music.beat(BeatFraction.Eighth))
        music.playTone(1046, music.beat(BeatFraction.Eighth))
        music.playTone(1174, music.beat(BeatFraction.Eighth))
        music.playTone(1318, music.beat(BeatFraction.Eighth))
        music.playTone(1397, music.beat(BeatFraction.Eighth))
        for (let index = 0; index < 3; index++) {
            music.playTone(1568, music.beat(BeatFraction.Quarter))
        }
        for (let index = 0; index < 3; index++) {
            music.playTone(2093, music.beat(BeatFraction.Quarter))
        }
        music.playTone(1976, music.beat(BeatFraction.Half))
        music.playTone(1760, music.beat(BeatFraction.Quarter))
        music.playTone(1568, music.beat(BeatFraction.Quarter))
        music.playTone(1318, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1318, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Half))
        music.playTone(1760, music.beat(BeatFraction.Quarter))
        for (let index = 0; index < 3; index++) {
            music.playTone(1568, music.beat(BeatFraction.Quarter))
        }
        for (let index = 0; index < 3; index++) {
            music.playTone(2093, music.beat(BeatFraction.Quarter))
        }
        music.playTone(1976, music.beat(BeatFraction.Half))
        music.playTone(1760, music.beat(BeatFraction.Quarter))
        music.playTone(1568, music.beat(BeatFraction.Quarter))
        music.playTone(1318, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Half))
        music.playTone(784, music.beat(BeatFraction.Quarter))
        music.playTone(1174, music.beat(BeatFraction.Quarter))
        music.playTone(1046, music.beat(BeatFraction.Quarter))
    }
})