input.onButtonPressed(Button.A, function () {
	music.setTempo(50)
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Half))
    music.playTone(784, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Half))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(880, music.beat(BeatFraction.Sixteenth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    music.playTone(1480, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.playTone(1480, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(1108, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(740, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 3; index++) {
        music.playTone(988, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(932, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 2; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(554, music.beat(BeatFraction.Sixteenth))
        music.playTone(466, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(466, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(466, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(330, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(554, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(554, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(392, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(740, music.beat(BeatFraction.Sixteenth))
        music.playTone(466, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(659, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 1; index++) {
        music.playTone(587, music.beat(BeatFraction.Sixteenth))
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
    }
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    for (let index = 0; index < 2; index++) {
        music.playTone(554, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    for (let index = 0; index < 2; index++) {
        music.playTone(494, music.beat(BeatFraction.Sixteenth))
        music.playTone(370, music.beat(BeatFraction.Sixteenth))
        music.playTone(294, music.beat(BeatFraction.Sixteenth))
    }
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(494, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(370, music.beat(BeatFraction.Sixteenth))
    music.playTone(466, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Whole))
    music.setTempo(35)
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.setTempo(37)
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(1064, music.beat(BeatFraction.Eighth))
    music.setTempo(26)
    music.playTone(1174, music.beat(BeatFraction.Sixteenth))
    music.playTone(1245, music.beat(BeatFraction.Sixteenth))
    music.playTone(1318, music.beat(BeatFraction.Sixteenth))
    music.setTempo(34)
    music.playTone(1397, music.beat(BeatFraction.Sixteenth))
    music.playTone(1480, music.beat(BeatFraction.Sixteenth))
    music.playTone(1568, music.beat(BeatFraction.Sixteenth))
    music.setTempo(30)
    music.playTone(1661, music.beat(BeatFraction.Eighth))
    music.changeTempoBy(20)
    for (let index = 0; index < 32; index++) {
        music.playTone(78, music.beat(BeatFraction.Eighth))
        music.playTone(104, music.beat(BeatFraction.Eighth))
    }
    music.setTempo(50)
    music.playTone(208, music.beat(BeatFraction.Sixteenth))
    music.playTone(233, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(311, music.beat(BeatFraction.Sixteenth))
    music.playTone(311, music.beat(BeatFraction.Sixteenth))
    music.playTone(415, music.beat(BeatFraction.Half))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Half))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Quarter))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(311, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(247, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Half))
    music.playTone(370, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.changeTempoBy(50)
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.setTempo(50)
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Quarter))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Quarter))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(311, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.playTone(247, music.beat(BeatFraction.Eighth))
    music.playTone(330, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(440, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Half))
    music.setTempo(50)
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.playTone(277, music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(466, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.changeTempoBy(50)
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.playTone(220, music.beat(BeatFraction.Sixteenth))
    music.setTempo(50)
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Quarter))
    music.playTone(311, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.changeTempoBy(50)
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.setTempo(50)
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.playTone(311, music.beat(BeatFraction.Eighth))
    music.playTone(415, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.changeTempoBy(50)
    music.playTone(440, music.beat(BeatFraction.Sixteenth))
    music.playTone(392, music.beat(BeatFraction.Sixteenth))
    music.playTone(349, music.beat(BeatFraction.Sixteenth))
    music.playTone(330, music.beat(BeatFraction.Sixteenth))
    music.playTone(294, music.beat(BeatFraction.Sixteenth))
    music.playTone(262, music.beat(BeatFraction.Sixteenth))
    music.playTone(247, music.beat(BeatFraction.Sixteenth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.setTempo(50)
    music.playTone(831, music.beat(BeatFraction.Half))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Half))
    music.playTone(698, music.beat(BeatFraction.Quarter))
    music.playTone(622, music.beat(BeatFraction.Sixteenth))
    music.playTone(587, music.beat(BeatFraction.Sixteenth))
    music.playTone(554, music.beat(BeatFraction.Quarter))
    music.playTone(415, music.beat(BeatFraction.Quarter))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(554, music.beat(BeatFraction.Eighth))
    music.playTone(349, music.beat(BeatFraction.Half))
    music.playTone(277, music.beat(BeatFraction.Quarter))
    music.playTone(208, music.beat(BeatFraction.Half))
    music.playTone(208, music.beat(BeatFraction.Quarter))
    music.changeTempoBy(5)
    music.playTone(622, music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Sixteenth))
    music.playTone(740, music.beat(BeatFraction.Sixteenth))
    music.playTone(784, music.beat(BeatFraction.Sixteenth))
    music.setTempo(50)
    music.playTone(831, music.beat(BeatFraction.Half))
    music.playTone(932, music.beat(BeatFraction.Half))
    music.playTone(622, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Sixteenth))
    music.playTone(659, music.beat(BeatFraction.Sixteenth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(831, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Quarter))
    music.setTempo(50)
    music.playTone(698, music.beat(BeatFraction.Half))
    music.rest(music.beat(BeatFraction.Half))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    for (let index = 0; index < 1; index++) {
        music.playTone(494, music.beat(BeatFraction.Eighth))
        music.playTone(740, music.beat(BeatFraction.Eighth))
        music.playTone(698, music.beat(BeatFraction.Eighth))
        music.playTone(587, music.beat(BeatFraction.Eighth))
        music.playTone(494, music.beat(BeatFraction.Eighth))
    }
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(370, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(880, music.beat(BeatFraction.Eighth))
    music.playTone(587, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.playTone(349, music.beat(BeatFraction.Quarter))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(740, music.beat(BeatFraction.Quarter))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(622, music.beat(BeatFraction.Eighth))
    music.playTone(494, music.beat(BeatFraction.Quarter))
    music.playTone(370, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Eighth))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(784, music.beat(BeatFraction.Quarter))
    music.playTone(698, music.beat(BeatFraction.Eighth))
    music.playTone(659, music.beat(BeatFraction.Eighth))
    music.playTone(523, music.beat(BeatFraction.Quarter))
    music.playTone(392, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.rest(music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.rest(music.beat(BeatFraction.Eighth))
    music.playTone(988, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Eighth))
    music.playTone(1174, music.beat(BeatFraction.Quarter))
    music.playTone(1046, music.beat(BeatFraction.Quarter))
    music.playTone(988, music.beat(BeatFraction.Quarter))
})